// API Service
export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_RESPONSE = 'RECEIVE_RESPONSE';

// Authentication
export const SET_AUTHENTICATED_STATUS = 'SET_AUTHENTICATED_STATUS';
export const SET_AUTHENTICATION_ERROR = 'SET_AUTHENTICATION_ERROR';

export const SET_SUBMISSION_ERROR = 'SET_SUBMISSION_ERROR';
export const SET_SUCCESFUL_SUBMISSION= 'SET_SUCCESFUL_SUBMISSION';

// File Manager
export const UPDATE_PAGE_NUMBER = 'UPDATE_PAGE_NUMBER';
export const UPDATE_ITEMS_PER_PAGE = 'UPDATE_ITEMS_PER_PAGE';
